[ADD] InputWithSuggestions component
unipartdigital/workflows_engine pull request #46
Opened 2021-03-29 11:56 UTC by PeterAlabaster

User-story: 13284

Signed-off-by: Peter Alabaster <peter.alabaster@unipart.io>

2021-03-29 12:08 UTC, unirho requested changes

2021-03-29 12:08 UTC, unirho commented on docs/source/primitives.rst
> +Input with Suggestions
need to add a link to the jsonschema

2021-03-29 12:26 UTC, unirho approved these changes

2021-03-30 08:37 UTC, apatrick88 approved these changes

2021-03-31 16:25 UTC, merged